[build]
  command = "flutter build web --release"
  publish = "build/web"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"

[[headers]]
  for = "/*.wasm"
  [headers.values]
    Content-Type = "application/wasm"
    Cross-Origin-Resource-Policy = "cross-origin"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"
